project:
  type: website
  output-dir: docs

website:
  favicon: images/ser.png
  title: "Mini-Curso - Explorando finanças com R"
  navbar:
    logo: images/ser.png
    left:
      - href: index.qmd
        text: Início
        icon: bi-house
      - href: apresentacao.qmd
        text: Apresentação
        icon: bi-file-earmark-text
      - href: exercicios.qmd
        text: Exercícios
        icon: bi-file-earmark-text
      - href: dashboard.qmd
        text: Dashboard
        icon: bi-file-earmark-text
    right: 
      - href: https://github.com/nextmarte
        text: GitHub
        icon: bi-github

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




