---
title: "Mini-curso de finanças com R"
bibliography: references.bib
---

# Bem-vindo(a)!!

Neste curso você aprenderá a utilizar o R para análise de dados financeiros. O curso terá duração de 3 horas e será apresentado seguindo o roteiro abaixo:

1.  Relembrar conceitos de finanças e aplicar o R na análise e visualização de seu portfólio.

2.  Importar os preços dos ativos da internet direto do yahoo.com

3.  Transformar os preços diários em mensais e obter os retornos.

4.  Visualização dos dados.

5.  Retorno da carteira

6.  Visualizar o retorno da carteira.

7.  Análise do risco.

8.  Beta do portfólio e de cada ativo.

9.  Índice sharpe

10. Aprender a criar um dashboard com seus dados e gráficos.

## Pré-requisitos

Esperamos que você já tenha tido contato com R e Quarto. Um computador com acesso à internet para acessar o ambiente de desenvolvimento Posit Cloud ou baixar o repositorio do curso.

## Preparação

Para se preparar para o curso, você pode baixar o repositório do curso no link abaixo:

[Repositório no GitHub](https://github.com/nextmarte/MiniCursoFinSER)

[Link para o ambiente de desenvolvimento Posit Cloud](https://posit.cloud/content/8286998)

## Lista dos pacotes e livros usados na elaboração deste curso

Tidyverse [@tidyverse], Quantmod[@quantmod], timetk [@timetk], plotly [@plotly], PerformanceAnalytics [@PerformanceAnalytics], DT [@DT] e Reproducible Finance with R [@regenstein2019]

##  Referências